### ISSUE TITLE
na installatie 404

### ISSUE THREAD

**Issue by raoulguillermo** [tradetracker-com/magento1#1]
Hi, 

Ik krijg na de installatie op magento 1.9 een 404 error. 
Ben ik iets vergeten?

**Comment by Frank-Magmodules** [comment]
Hi @raoulguillermo ,   
  
Dank voor je bericht, ik sluit deze issue omdat we deze per mail hebben opgelost. De oplossing was eenvoudig; door even uit te loggen en opnieuw in te loggen in de backend, worden de gebruikersrechten juist toegewezen en is de configuratie zichtbaar.
